version: '2'

services:
  # Postgres
  db:
    image: postgres:9.4

  # Onstart commands
  migration:
    command: python manage.py migrate --noinput
    env_file:
      - secret.env
    image: warehouse:latest
    volumes:
      - .:/app/
    depends_on:
      - db

  # Web
  warehouse:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - secret.env
    image: warehouse:latest
    ports:
     - 8000:8000
    depends_on:
      - db
      - migration
    volumes:
      - .:/app/

  # Celery worker
  celery-worker:
    build: .
    command: python manage.py celery worker --loglevel=INFO
    image: warehouse:latest
    env_file:
      - secret.env
    environment:
      - C_FORCE_ROOT=true
    depends_on:
      - db
      - migration
    volumes:
      - .:/app/

  # Celery beat
  celery-beat:
    build: .
    command: python manage.py celery beat
    image: warehouse:latest
    env_file:
      - secret.env
    environment:
      - C_FORCE_ROOT=true
    depends_on:
      - db
      - migration
      - celery-worker
    volumes:
      - .:/app/
